import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import Carousel from "@/components/Carusel/Carousel";
import Home1 from "@/components/Home/Home1";
import Home2 from "@/components/Home/Home2";
import Home3 from "@/components/Home/Home3";
import Otzyvy from "@/components/Otzyvy/Otzyvy";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <Carousel />
      <Home1 />
      <Home2 />
      <Home3 />
      <Otzyvy/>
      {/* <Footer/> */}
    </>
  );
}
